### ISSUE TITLE
When face recovery is enabled codeformer

### ISSUE THREAD

**Issue by konservat0r** [AUTOMATIC1111/stable-diffusion-webui-feature-showcase#15]
RuntimeError: unexpected EOF, expected 69945 more bytes. The file might be corrupted.

**Comment by agarzon** [comment]
I believed the issue must be reported here https://github.com/sczhou/CodeFormer

This repository is only a showcase for the [stable-diffusion-webui project](https://github.com/AUTOMATIC1111/stable-diffusion-webui).
